---
- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: docker
    default_container_image: drorvt/drortask:05baa046803a2ae3334a6d22bd1436a0c7cf7c67
    default_container_command: curl 127.0.0.1:8000

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    
    - name: Checking docker on latest version
      apt: name=docker.io state=latest

    - name: Checking python
      apt: name=python state=latest

    - name: Checking docker-compose on latest version
      apt: name=docker-compose state=latest

    # Pull image specified by variable default_image from the Docker Hub
    - name:   
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Creates the number of containers defined by the variable create_containers, using default values
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
